=== acmemud/acme-platform/.etc/command.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="commands">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="command" type="command" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="command">
    <xsd:sequence>
      <xsd:element name="secondaryVerb" maxOccurs="unbounded" minOccurs="0">
        <xsd:complexType>
          <xsd:attribute name="verb" type="xsd:string"></xsd:attribute>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="fieldList" type="fieldList" maxOccurs="1" minOccurs="0"></xsd:element>
      <xsd:element name="argList" type="argList" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      <xsd:element name="optSet" type="optSet" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      <xsd:element name="syntax" type="syntax" maxOccurs="unbounded" minOccurs="1"></xsd:element>
      <xsd:element name="validate" type="validate" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      <xsd:element name="subcommand" type="command" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string"></xsd:attribute>
    <xsd:attribute name="ref" type="xsd:string"></xsd:attribute>
    <xsd:attribute name="primaryVerb" type="xsd:string"></xsd:attribute>
    <xsd:attribute name="parser" type="xsd:string"></xsd:attribute>
    <xsd:attribute name="controller" type="xsd:string"></xsd:attribute>
  </xsd:complexType>

  <xsd:complexType name="fieldList">
    <xsd:sequence>
      <xsd:element name="field" type="field" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="argList">
    <xsd:sequence>
      <xsd:element name="arg" type="arg" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string"></xsd:attribute>
    <xsd:attribute name="ref" type="xsd:string"></xsd:attribute>
  </xsd:complexType>

  <xsd:complexType name="optSet">
    <xsd:sequence>
      <xsd:element name="opt" type="opt" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      <xsd:element name="longopt" type="xsd:string" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string"></xsd:attribute>
    <xsd:attribute name="ref" type="xsd:string"></xsd:attribute>
  </xsd:complexType>

  <xsd:complexType name="field">
    <xsd:sequence>
      <xsd:element name="validate" type="validate" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      <xsd:element name="prompt" type="prompt" maxOccurs="1" minOccurs="0"></xsd:element>
      <xsd:element name="enum" type="enum" maxOccurs="1" minOccurs="0"></xsd:element>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string"></xsd:attribute>
    <xsd:attribute name="type" type="type"></xsd:attribute>
    <xsd:attribute name="required" type="required"></xsd:attribute>
  </xsd:complexType>

  <xsd:complexType name="arg">
    <xsd:complexContent>
      <xsd:extension base="field">
        <xsd:attribute name="fieldRef" type="xsd:string"></xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="opt">
    <xsd:complexContent>
      <xsd:extension base="field">
        <xsd:attribute name="fieldRef" type="xsd:string"></xsd:attribute>
        <xsd:attribute name="param">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="1"></xsd:maxLength>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="longopt">
    <xsd:complexContent>
      <xsd:extension base="field">
        <xsd:attribute name="fieldRef" type="xsd:string"></xsd:attribute>
        <xsd:attribute name="param" type="xsd:string"></xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="syntax">
    <xsd:sequence>
      <xsd:element name="validate" type="validate" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      <xsd:element name="argList" type="argList" maxOccurs="1" minOccurs="0"></xsd:element>
      <xsd:element name="optSet" type="optSet" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      <xsd:element name="opt" type="opt" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      <xsd:element name="longopt" type="longopt" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      <xsd:element name="subcommand" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
    </xsd:sequence>
    <xsd:attribute name="args">
      <xsd:simpleType>
        <xsd:restriction base="xsd:int">
          <xsd:minInclusive value="0"></xsd:minInclusive>
        </xsd:restriction>
      </xsd:simpleType>
    </xsd:attribute>
    <xsd:attribute name="minArgs">
      <xsd:simpleType>
        <xsd:restriction base="xsd:int">
          <xsd:minInclusive value="0"></xsd:minInclusive>
        </xsd:restriction>
      </xsd:simpleType>
    </xsd:attribute>
    <xsd:attribute name="maxArgs">
      <xsd:simpleType>
        <xsd:restriction base="xsd:int">
          <xsd:minInclusive value="0"></xsd:minInclusive>
        </xsd:restriction>
      </xsd:simpleType>
    </xsd:attribute>
    <xsd:attribute name="pattern" type="xsd:string"></xsd:attribute>
    <xsd:attribute name="format" type="format"></xsd:attribute>
  </xsd:complexType>

  <xsd:complexType name="validate">
    <xsd:sequence>
      <xsd:element name="param" maxOccurs="unbounded" minOccurs="0">
        <xsd:complexType>
          <xsd:attribute name="value" type="xsd:string"></xsd:attribute>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="validator" type="xsd:string"></xsd:attribute>
    <xsd:attribute name="fail" type="xsd:string"></xsd:attribute>
  </xsd:complexType>

  <xsd:complexType name="prompt">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
      <xsd:attribute name="noecho" type="xsd:boolean"></xsd:attribute>
      <xsd:attribute name="showAbort" type="xsd:boolean"></xsd:attribute>
      <xsd:attribute name="showEnum">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="false"></xsd:enumeration>
            <xsd:enumeration value="short"></xsd:enumeration>
            <xsd:enumeration value="long"></xsd:enumeration>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="maxRetry">
        <xsd:simpleType>
          <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="0"></xsd:minInclusive>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:simpleType name="type">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="bool"></xsd:enumeration>
      <xsd:enumeration value="int"></xsd:enumeration>
      <xsd:enumeration value="float"></xsd:enumeration>
      <xsd:enumeration value="string"></xsd:enumeration>
      <xsd:enumeration value="enum"></xsd:enumeration>
      <xsd:enumeration value="object"></xsd:enumeration>
      <xsd:enumeration value="objects"></xsd:enumeration>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="required">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="true"></xsd:enumeration>
      <xsd:enumeration value="prompt"></xsd:enumeration>
      <xsd:enumeration value="false"></xsd:enumeration>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="enum">
    <xsd:sequence>
      <xsd:element name="value" maxOccurs="unbounded" minOccurs="1">
        <xsd:complexType>
          <xsd:attribute name="value" type="xsd:string"></xsd:attribute>
          <xsd:attribute name="label" type="xsd:string"></xsd:attribute>
          <xsd:attribute name="type" type="type"></xsd:attribute>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string"></xsd:attribute>
    <xsd:attribute name="ref" type="xsd:string"></xsd:attribute>
    <xsd:attribute name="multi" type="xsd:boolean"></xsd:attribute>
    <xsd:attribute name="delim" type="xsd:string"></xsd:attribute>
  </xsd:complexType>

  <xsd:simpleType name="format">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="explode"></xsd:enumeration>
      <xsd:enumeration value="sscanf"></xsd:enumeration>
      <xsd:enumeration value="parse_command"></xsd:enumeration>
      <xsd:enumeration value="regexp"></xsd:enumeration>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== acmemud/acme-platform/.bin/avatar/avatar.xml
<?xml version="1.0" encoding="UTF-8"?>
<commands 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/bobalu113/gabbo/master/mudlib/platform/.etc/command.xsd">

  <command primaryVerb="login" controller="login">
    <fieldList>
      <field id="username" type="string" required="prompt">
        <validate validator="not_empty"></validate>
        <validate validator="max_length">
          <param value="12"/>
          <fail>Maximum username length is 12 characters.</fail>
        </validate>
        <validate validator="is_user">
          <fail>That username does not exist.</fail>
        </validate>
        <prompt maxRetry="3">Enter your name: </prompt>
      </field>
      <field id="password" type="string" required="prompt">
        <validate validator="not_empty"></validate>
        <validate validator="authenticated">
          <fail>Wrong password.</fail>
        </validate>
        <prompt noecho="true" maxRetry="3">Enter your password: </prompt>
      </field>
    </fieldList>
    <syntax minArgs="0" maxArgs="1">
      <argList>
        <arg fieldRef="username"></arg>
      </argList>
    </syntax>
  </command>

  <command primaryVerb="register" controller="register">
    <validate validator="passwords_match">
      <fail>Passwords do not match.</fail>
    </validate>
    <fieldList>
      <field id="username" type="string" required="prompt">
        <validate validator="not_empty"></validate>
        <validate validator="max_length">
          <param value="12"/>
        </validate>
        <validate validator="available_username">
          <fail>That username already exists.</fail>
        </validate>
        <prompt maxRetry="3">Enter your name: </prompt>
      </field>
      <field id="password" type="string" required="prompt">
        <validate validator="not_empty"></validate>
        <prompt noecho="true" maxRetry="3">Enter your password: </prompt>
      </field>
      <field id="confirmPassword" type="string" required="prompt">
        <validate validator="not_empty"></validate>
        <prompt noecho="true" maxRetry="3">Confirm your password: </prompt>
      </field>
    </fieldList>
    <syntax minArgs="0" maxArgs="1">
      <argList>
        <arg fieldRef="username"></arg>
      </argList>
    </syntax>
  </command>

  <command primaryVerb="guest" controller="guest">
    <syntax args="0"></syntax>
  </command>

  <command primaryVerb="quit" controller="quit">
    <syntax args="0"></syntax>
  </command>

</commands>
